name: Documentation Issue
description: Report incorrect, missing, or unclear documentation
title: "[Docs]: "
labels: ["documentation", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve Cupcake's documentation! Clear docs help everyone.

  - type: dropdown
    id: type
    attributes:
      label: Documentation Issue Type
      description: What kind of documentation issue is this?
      options:
        - Incorrect information
        - Missing documentation
        - Unclear or confusing
        - Outdated content
        - Typo or grammatical error
        - Broken link
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: If the issue is related to a certain page, provide a URL.
      placeholder: "https://cupcake.eqtylab.io/"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the documentation issue in detail.
      placeholder: |
        What's wrong with the current documentation?
        What information is missing or incorrect?
    validations:
      required: true

  - type: textarea
    id: suggested
    attributes:
      label: Suggested Improvement
      description: If you have ideas for how to fix or improve the documentation, please share them.
      placeholder: |
        How should the documentation be improved?
        What content should be added or changed?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references that might help.
